### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by sftblw** [disjukr/makise#6]
라이브러리 쪽의 라이선스가 어떻게 되는지 알 수 있을까요?

**Comment by disjukr** [comment]
MIT인 것 같네용(?) https://github.com/disjukr/makise/blob/master/package.json#L25

**Comment by disjukr** [comment]
`만든이가 열심히 개밥먹기하고 있으니 믿고 사용하셔도 좋습니다(?)` 이제 관리 안한지 3년이 넘었으니 믿으시면 안됩니다(??)
